import fs from "node:fs";
const dir = process.argv[2] + "\\h5\\static\\js";
const s = fs.readFileSync(dir + "\\index.js", "utf8");
const a0 = s.indexOf('static/js/"');
const a1 = s.indexOf('}[e]||e)', a0);
const a2 = s.indexOf('[e]+".js"', a1);
const nameObj = s.slice(s.indexOf("({", a0) + 1, a1);
const hashStart = s.indexOf("+{", a1);
const hashObj = s.slice(s.indexOf("{", hashStart), a2);
const names = {};
for (const m of nameObj.matchAll(/"([^"]+)":"([^"]+)"/g)) names[m[1]] = m[2];
const hashes = {};
for (const m of hashObj.matchAll(/"([^"]+)":"([^"]+)"/g)) hashes[m[1]] = m[2];
const ids = Object.keys(names);
console.log("IDS=" + ids.length + " HASHES=" + Object.keys(hashes).length);
const files = ids.map(id => `${names[id]}.${hashes[id]}.js`).filter(f => !f.includes("undefined"));
fs.writeFileSync(process.argv[2] + "\\h5_files.txt", files.join("\n"), "utf8");
console.log("FILES=" + files.length);
console.log("PADK=" + files.filter(f=>/padk/i.test(f)).join("\n"));
